export type Phrase = {
  english: string;
  italian: string;
  japanese: string;
  czech: string;
  portuguese: string;
  spanish: string;
  category: string;
};

export const phrases: Phrase[] = [
  // Common Phrases
  {
    english: 'Excuse me',
    italian: 'Scusi',
    japanese: 'すみません [sumimasen]',
    czech: 'Prominťte',
    portuguese: 'Com licença',
    spanish: 'Disculpe',
    category: 'Basic',
  },
  {
    english: "I'm sorry",
    italian: 'Mi dispiace',
    japanese: 'ごめんなさい [gomen nasai]',
    czech: 'Promiňte',
    portuguese: 'Desculpe',
    spanish: 'Lo siento',
    category: 'Basic',
  },
  {
    english: 'Help',
    italian: 'Aiuto',
    japanese: '助けて [tasukete]',
    czech: 'Pomoc',
    portuguese: 'Ajuda',
    spanish: 'Ayuda',
    category: 'Basic',
  },
  {
    english: "I don't understand",
    italian: 'Non capisco',
    japanese: 'わかりません [wakarimasen]',
    czech: 'Nerozumím',
    portuguese: 'Não entendo',
    spanish: 'No entiendo',
    category: 'Basic',
  },
  {
    english: 'Do you speak English?',
    italian: 'Parla inglese?',
    japanese: '英語を話せますか [eigo wo hanasemasu ka]',
    czech: 'Mluvite anglicky?',
    portuguese: 'Você fala inglês?',
    spanish: '¿Habla inglés?',
    category: 'Basic',
  },
  {
    english: 'How much?',
    italian: 'Quanto costa?',
    japanese: 'いくらですか [ikura desu ka]',
    czech: 'Kolik to stojí?',
    portuguese: 'Quanto custa?',
    spanish: '¿Cuánto cuesta?',
    category: 'Basic',
  },
  {
    english: 'Where is...?',
    italian: "Dov'è...?",
    japanese: '...はどこですか [...wa doko desu ka]',
    czech: 'Kde je...?',
    portuguese: 'Onde é...?',
    spanish: '¿Dónde está...?',
    category: 'Basic',
  },
  {
    english: 'I would like...',
    italian: 'Vorrei...',
    japanese: '...をください [...wo kudasai]',
    czech: 'Chtěl bych...',
    portuguese: 'Eu gostaria...',
    spanish: 'Me gustaría...',
    category: 'Basic',
  },
  {
    english: 'Can you help me?',
    italian: 'Può aiutarmi?',
    japanese: '手伝ってくれますか [tetsudatte kuremasu ka]',
    czech: 'Můžete mi pomoci?',
    portuguese: 'Você pode me ajudar?',
    spanish: '¿Puede ayudarme?',
    category: 'Basic',
  },
  {
    english: 'Nice to meet you',
    italian: 'Piacere',
    japanese: 'はじめまして [hajimemashite]',
    czech: 'Těší mě',
    portuguese: 'Prazer em conhecê-lo',
    spanish: 'Mucho gusto',
    category: 'Basic',
  },

  // Restaurant Phrases
  {
    english: 'Table for two, please',
    italian: 'Un tavolo per due, per favore',
    japanese: '二人用のテーブルをお願いします [futari you no teeburu wo onegaishimasu]',
    czech: 'Stůl pro dva, prosím',
    portuguese: 'Mesa para dois, por favor',
    spanish: 'Mesa para dos, por favor',
    category: 'Restaurant',
  },
  {
    english: 'The bill, please',
    italian: 'Il conto, per favore',
    japanese: 'お会計をお願いします [okaikei wo onegaishimasu]',
    czech: 'Účet, prosím',
    portuguese: 'A conta, por favor',
    spanish: 'La cuenta, por favor',
    category: 'Restaurant',
  },
  {
    english: 'The menu, please',
    italian: 'Il menù, per favore',
    japanese: 'メニューをお願いします [menyuu wo onegaishimasu]',
    czech: 'Menu, prosím',
    portuguese: 'O cardápio, por favor',
    spanish: 'El menú, por favor',
    category: 'Restaurant',
  },
  {
    english: "I'll have this",
    italian: 'Prendo questo',
    japanese: 'これにします [kore ni shimasu]',
    czech: 'Dám si tohle',
    portuguese: 'Vou querer isto',
    spanish: 'Voy a tomar esto',
    category: 'Restaurant',
  },
  {
    english: 'Is this spicy?',
    italian: 'È piccante?',
    japanese: '辛いですか [karai desu ka]',
    czech: 'Je to pálivé?',
    portuguese: 'É picante?',
    spanish: '¿Está picante?',
    category: 'Restaurant',
  },
  {
    english: 'No meat, please',
    italian: 'Senza carne, per favore',
    japanese: 'お肉なしでお願いします [oniku nashi de onegaishimasu]',
    czech: 'Bez masa, prosím',
    portuguese: 'Sem carne, por favor',
    spanish: 'Sin carne, por favor',
    category: 'Restaurant',
  },
  {
    english: 'More water, please',
    italian: 'Ancora acqua, per favore',
    japanese: 'お水をもう一杯お願いします [omizu wo mou ippai onegaishimasu]',
    czech: 'Ještě vodu, prosím',
    portuguese: 'Mais água, por favor',
    spanish: 'Más agua, por favor',
    category: 'Restaurant',
  },
  {
    english: 'This is delicious',
    italian: 'È delizioso',
    japanese: '美味しいです [oishii desu]',
    czech: 'Tohle je chutné',
    portuguese: 'Isto está delicioso',
    spanish: 'Esto está delicioso',
    category: 'Restaurant',
  },
  {
    english: 'Do you have WiFi?',
    italian: 'Avete WiFi?',
    japanese: 'WiFiはありますか [WiFi wa arimasu ka]',
    czech: 'Máte WiFi?',
    portuguese: 'Vocês têm WiFi?',
    spanish: '¿Tienen WiFi?',
    category: 'Restaurant',
  },
  {
    english: 'Can I pay by card?',
    italian: 'Posso pagare con carta?',
    japanese: 'カードで払えますか [kaado de haraemasu ka]',
    czech: 'Mohu platit kartou?',
    portuguese: 'Posso pagar com cartão?',
    spanish: '¿Puedo pagar con tarjeta?',
    category: 'Restaurant',
  },

  // Travel Phrases
  {
    english: 'One ticket, please',
    italian: 'Un biglietto, per favore',
    japanese: '切符を一枚お願いします [kippu wo ichimai onegaishimasu]',
    czech: 'Jeden lístek, prosím',
    portuguese: 'Um bilhete, por favor',
    spanish: 'Un boleto, por favor',
    category: 'Travel',
  },
  {
    english: 'Return ticket',
    italian: 'Biglietto di andata e ritorno',
    japanese: '往復切符 [oufuku kippu]',
    czech: 'Zpáteční lístek',
    portuguese: 'Bilhete de ida e volta',
    spanish: 'Boleto de ida y vuelta',
    category: 'Travel',
  },
  {
    english: 'What time is the train?',
    italian: 'A che ora è il treno?',
    japanese: '電車は何時ですか [densha wa nanji desu ka]',
    czech: 'V kolik jede vlak?',
    portuguese: 'Que horas é o trem?',
    spanish: '¿A qué hora es el tren?',
    category: 'Travel',
  },
  {
    english: 'Platform number?',
    italian: 'Che binario?',
    japanese: '何番線ですか [nanban sen desu ka]',
    czech: 'Číslo nástupiště?',
    portuguese: 'Número da plataforma?',
    spanish: '¿Número de andén?',
    category: 'Travel',
  },
  {
    english: 'Is this seat free?',
    italian: 'È libero questo posto?',
    japanese: 'この席は空いていますか [kono seki wa aiteimasu ka]',
    czech: 'Je tohle místo volné?',
    portuguese: 'Este lugar está livre?',
    spanish: '¿Está libre este asiento?',
    category: 'Travel',
  },
  {
    english: 'I have a reservation',
    italian: 'Ho una prenotazione',
    japanese: '予約があります [yoyaku ga arimasu]',
    czech: 'Mám rezervaci',
    portuguese: 'Tenho uma reserva',
    spanish: 'Tengo una reservación',
    category: 'Travel',
  },
  {
    english: 'Check-in, please',
    italian: 'Check-in, per favore',
    japanese: 'チェックインお願いします [chekkuin onegaishimasu]',
    czech: 'Check-in, prosím',
    portuguese: 'Check-in, por favor',
    spanish: 'Check-in, por favor',
    category: 'Travel',
  },
  {
    english: 'My passport',
    italian: 'Il mio passaporto',
    japanese: '私のパスポート [watashi no pasupooto]',
    czech: 'Můj pas',
    portuguese: 'Meu passaporte',
    spanish: 'Mi pasaporte',
    category: 'Travel',
  },
  {
    english: 'Which gate?',
    italian: 'Che gate?',
    japanese: '何番ゲートですか [nanban geeto desu ka]',
    czech: 'Který gate?',
    portuguese: 'Qual portão?',
    spanish: '¿Cuál puerta?',
    category: 'Travel',
  },
  {
    english: 'Is the flight delayed?',
    italian: 'Il volo è in ritardo?',
    japanese: 'フライトは遅れていますか [furaito wa okurete imasu ka]',
    czech: 'Je let opožděný?',
    portuguese: 'O voo está atrasado?',
    spanish: '¿Está retrasado el vuelo?',
    category: 'Travel',
  },

  // Shopping Phrases
  {
    english: 'How much is this?',
    italian: 'Quanto costa questo?',
    japanese: 'これはいくらですか [kore wa ikura desu ka]',
    czech: 'Kolik tohle stojí?',
    portuguese: 'Quanto custa isto?',
    spanish: '¿Cuánto cuesta esto?',
    category: 'Shopping',
  },
  {
    english: 'Can I try this on?',
    italian: 'Posso provare questo?',
    japanese: 'これを試着できますか [kore wo shichaku dekimasu ka]',
    czech: 'Mohu si tohle zkusit?',
    portuguese: 'Posso experimentar isto?',
    spanish: '¿Puedo probarme esto?',
    category: 'Shopping',
  },
  {
    english: 'Do you have this in large?',
    italian: 'Avete questo in taglia grande?',
    japanese: 'これのLサイズはありますか [kore no L saizu wa arimasu ka]',
    czech: 'Máte tohle ve velikosti L?',
    portuguese: 'Vocês têm isto em tamanho grande?',
    spanish: '¿Tienen esto en talla grande?',
    category: 'Shopping',
  },
  {
    english: 'Different color?',
    italian: 'Colore diverso?',
    japanese: '違う色はありますか [chigau iro wa arimasu ka]',
    czech: 'Jiná barva?',
    portuguese: 'Cor diferente?',
    spanish: '¿Color diferente?',
    category: 'Shopping',
  },
  {
    english: 'Too expensive',
    italian: 'Troppo caro',
    japanese: '高すぎます [takasugimasu]',
    czech: 'Příliš drahé',
    portuguese: 'Muito caro',
    spanish: 'Muy caro',
    category: 'Shopping',
  },
  {
    english: "I'll take it",
    italian: 'Lo prendo',
    japanese: 'これにします [kore ni shimasu]',
    czech: 'Vezmu si to',
    portuguese: 'Vou levar',
    spanish: 'Me lo llevo',
    category: 'Shopping',
  },
  {
    english: 'Plastic bag, please',
    italian: 'Sacchetto di plastica, per favore',
    japanese: '袋をお願いします [fukuro wo onegaishimasu]',
    czech: 'Igelitku, prosím',
    portuguese: 'Saco plástico, por favor',
    spanish: 'Bolsa plástica, por favor',
    category: 'Shopping',
  },
  {
    english: 'Receipt, please',
    italian: 'Ricevuta, per favore',
    japanese: 'レシートをお願いします [reshiito wo onegaishimasu]',
    czech: 'Účtenku, prosím',
    portuguese: 'Recibo, por favor',
    spanish: 'Recibo, por favor',
    category: 'Shopping',
  },

  // Emergency Phrases
  {
    english: 'Call the police',
    italian: 'Chiama la polizia',
    japanese: '警察を呼んでください [keisatsu wo yonde kudasai]',
    czech: 'Zavolejte policii',
    portuguese: 'Chame a polícia',
    spanish: 'Llame a la policía',
    category: 'Emergency',
  },
  {
    english: 'I need a doctor',
    italian: 'Ho bisogno di un medico',
    japanese: '医者が必要です [isha ga hitsuyou desu]',
    czech: 'Potřebuji lékaře',
    portuguese: 'Preciso de um médico',
    spanish: 'Necesito un médico',
    category: 'Emergency',
  },
  {
    english: 'Call an ambulance',
    italian: "Chiama un'ambulanza",
    japanese: '救急車を呼んでください [kyuukyuusha wo yonde kudasai]',
    czech: 'Zavolejte záchrannáře',
    portuguese: 'Chame uma ambulância',
    spanish: 'Llame una ambulancia',
    category: 'Emergency',
  },
  {
    english: 'Fire!',
    italian: 'Fuoco!',
    japanese: '火事です [kaji desu]',
    czech: 'Hoří!',
    portuguese: 'Fogo!',
    spanish: '¡Fuego!',
    category: 'Emergency',
  },
  {
    english: "I'm lost",
    italian: 'Mi sono perso',
    japanese: '道に迷いました [michi ni mayoimashita]',
    czech: 'Ztratil jsem se',
    portuguese: 'Estou perdido',
    spanish: 'Estoy perdido',
    category: 'Emergency',
  },
  {
    english: 'My phone was stolen',
    italian: 'Mi hanno rubato il telefono',
    japanese: '携帯を盗まれました [keitai wo nusumaremashita]',
    czech: 'Ukradli mi telefon',
    portuguese: 'Roubaram meu telefone',
    spanish: 'Me robaron el teléfono',
    category: 'Emergency',
  },
  {
    english: 'I need the embassy',
    italian: "Ho bisogno dell'ambasciata",
    japanese: '大使館が必要です [taishikan ga hitsuyou desu]',
    czech: 'Potřebuji velvyslanectví',
    portuguese: 'Preciso da embaixada',
    spanish: 'Necesito la embajada',
    category: 'Emergency',
  },
  {
    english: 'I feel sick',
    italian: 'Mi sento male',
    japanese: '気分が悪いです [kibun ga warui desu]',
    czech: 'Cítím se špatně',
    portuguese: 'Sinto-me mal',
    spanish: 'Me siento mal',
    category: 'Emergency',
  },

  // Health Phrases
  {
    english: 'My head hurts',
    italian: 'Mi fa male la testa',
    japanese: '頭が痛いです [atama ga itai desu]',
    czech: 'Bolí mě hlava',
    portuguese: 'Minha cabeça dói',
    spanish: 'Me duele la cabeza',
    category: 'Health',
  },
  {
    english: 'I have a fever',
    italian: 'Ho la febbre',
    japanese: '熱があります [netsu ga arimasu]',
    czech: 'Mám horŭčku',
    portuguese: 'Tenho febre',
    spanish: 'Tengo fiebre',
    category: 'Health',
  },
  {
    english: 'I feel dizzy',
    italian: 'Mi gira la testa',
    japanese: 'めまいがします [memai ga shimasu]',
    czech: 'Je mi závratě',
    portuguese: 'Sinto-me tonto',
    spanish: 'Me siento mareado',
    category: 'Health',
  },
  {
    english: 'I need medicine',
    italian: 'Ho bisogno di medicine',
    japanese: '薬が必要です [kusuri ga hitsuyou desu]',
    czech: 'Potřebuji léky',
    portuguese: 'Preciso de remédios',
    spanish: 'Necesito medicina',
    category: 'Health',
  },
  {
    english: 'Where is the pharmacy?',
    italian: "Dov'è la farmacia?",
    japanese: '薬局はどこですか [yakkyoku wa doko desu ka]',
    czech: 'Kde je lékárna?',
    portuguese: 'Onde é a farmácia?',
    spanish: '¿Dónde está la farmacia?',
    category: 'Health',
  },
  {
    english: "I'm allergic to...",
    italian: 'Sono allergico a...',
    japanese: '...にアレルギーがあります [...ni areruggii ga arimasu]',
    czech: 'Jsem alergický na...',
    portuguese: 'Sou alérgico a...',
    spanish: 'Soy alérgico a...',
    category: 'Health',
  },
  {
    english: 'Call a doctor',
    italian: 'Chiama un dottore',
    japanese: '医者を呼んでください [isha wo yonde kudasai]',
    czech: 'Zavolejte lékaře',
    portuguese: 'Chame um médico',
    spanish: 'Llame un médico',
    category: 'Health',
  },
  {
    english: 'I cut my finger',
    italian: 'Mi sono tagliato il dito',
    japanese: '指を切りました [yubi wo kirimashita]',
    czech: 'Řízl jsem si prst',
    portuguese: 'Cortei meu dedo',
    spanish: 'Me corté el dedo',
    category: 'Health',
  },

  // Weather Phrases
  {
    english: "What's the weather like?",
    italian: "Com'è il tempo?",
    japanese: '天気はどうですか [tenki wa dou desu ka]',
    czech: 'Jaké je počasí?',
    portuguese: 'Como está o tempo?',
    spanish: '¿Cómo está el clima?',
    category: 'Weather',
  },
  {
    english: "It's raining",
    italian: 'Sta piovendo',
    japanese: '雨が降っています [ame ga futte imasu]',
    czech: 'Prší',
    portuguese: 'Está chovendo',
    spanish: 'Está lloviendo',
    category: 'Weather',
  },
  {
    english: 'I need an umbrella',
    italian: 'Ho bisogno di un ombrello',
    japanese: '傘が必要です [kasa ga hitsuyou desu]',
    czech: 'Potřebuji deštník',
    portuguese: 'Preciso de um guarda-chuva',
    spanish: 'Necesito un paraguas',
    category: 'Weather',
  },

  // Technology Phrases
  {
    english: 'My phone is dead',
    italian: 'Il mio telefono è scarico',
    japanese: '携帯の電池が切れました [keitai no denchi ga kiremashita]',
    czech: 'Můj telefon je vybitý',
    portuguese: 'Meu telefone está sem bateria',
    spanish: 'Mi teléfono está muerto',
    category: 'Technology',
  },
  {
    english: 'Where can I charge this?',
    italian: 'Dove posso caricare questo?',
    japanese: 'これをどこで充電できますか [kore wo doko de juuden dekimasu ka]',
    czech: 'Kde to mohu nabít?',
    portuguese: 'Onde posso carregar isto?',
    spanish: '¿Dónde puedo cargar esto?',
    category: 'Technology',
  },
  {
    english: "What's the WiFi password?",
    italian: 'Qual è la password del WiFi?',
    japanese: 'WiFiのパスワードは何ですか [WiFi no pasuwaado wa nan desu ka]',
    czech: 'Jaké je heslo k WiFi?',
    portuguese: 'Qual é a senha do WiFi?',
    spanish: '¿Cuál es la contraseña del WiFi?',
    category: 'Technology',
  },
  {
    english: 'Can you take a photo?',
    italian: 'Puoi fare una foto?',
    japanese: '写真を撮ってもらえますか [shashin wo totte moraemasu ka]',
    czech: 'Můžete vyčit fotku?',
    portuguese: 'Você pode tirar uma foto?',
    spanish: '¿Puede tomar una foto?',
    category: 'Technology',
  },

  // Transportation Phrases
  {
    english: 'How do I get to...?',
    italian: 'Come arrivo a...?',
    japanese: '...にはどう行きますか [...ni wa dou ikimasu ka]',
    czech: 'Jak se dostanu do...?',
    portuguese: 'Como chego a...?',
    spanish: '¿Cómo llego a...?',
    category: 'Transportation',
  },
  {
    english: 'Is it far?',
    italian: 'È lontano?',
    japanese: '遠いですか [tooi desu ka]',
    czech: 'Je to daleko?',
    portuguese: 'É longe?',
    spanish: '¿Está lejos?',
    category: 'Transportation',
  },

  // Money Phrases
  {
    english: 'Where is the ATM?',
    italian: "Dov'è il bancomat?",
    japanese: 'ATMはどこですか [ATM wa doko desu ka]',
    czech: 'Kde je bankomat?',
    portuguese: 'Onde é o caixa eletrônico?',
    spanish: '¿Dónde está el cajero?',
    category: 'Money',
  },
  {
    english: 'Can you break this bill?',
    italian: 'Può cambiare questa banconota?',
    japanese: 'この札を崩してもらえますか [kono satsu wo kuzushite moraemasu ka]',
    czech: 'Můžete rozměnit tuto bankovku?',
    portuguese: 'Pode trocar esta nota?',
    spanish: '¿Puede cambiar este billete?',
    category: 'Money',
  },
  {
    english: 'Is tip included?',
    italian: 'La mancia è inclusa?',
    japanese: 'チップは含まれていますか [chippu wa fukumarete imasu ka]',
    czech: 'Je spršné začenuto?',
    portuguese: 'A gorjeta está incluída?',
    spanish: '¿Está incluida la propina?',
    category: 'Money',
  },
  {
    english: 'How much is it?',
    italian: 'Quanto costa?',
    japanese: 'いくらですか [ikura desu ka]',
    czech: 'Kolik to stojí?',
    portuguese: 'Quanto custa?',
    spanish: '¿Cuánto cuesta?',
    category: 'Money',
  },

  // Directions Phrases
  {
    english: 'Turn left',
    italian: 'Gira a sinistra',
    japanese: '左に曲がって [hidari ni magatte]',
    czech: 'Zahniťte doleva',
    portuguese: 'Vire à esquerda',
    spanish: 'Gire a la izquierda',
    category: 'Directions',
  },
  {
    english: 'Turn right',
    italian: 'Gira a destra',
    japanese: '右に曲がって [migi ni magatte]',
    czech: 'Zahniťte doprava',
    portuguese: 'Vire à direita',
    spanish: 'Gire a la derecha',
    category: 'Directions',
  },
  {
    english: 'Go straight',
    italian: 'Va dritto',
    japanese: 'まっすぐ行って [massugu itte]',
    czech: 'Jděte rovně',
    portuguese: 'Siga em frente',
    spanish: 'Siga derecho',
    category: 'Directions',
  },
  {
    english: "It's on the right",
    italian: 'È sulla destra',
    japanese: '右側にあります [migigawa ni arimasu]',
    czech: 'Je to vpravo',
    portuguese: 'Está à direita',
    spanish: 'Está a la derecha',
    category: 'Directions',
  },
  {
    english: "I'm looking for...",
    italian: 'Sto cercando...',
    japanese: '...を探しています [...wo sagashite imasu]',
    czech: 'Hledám...',
    portuguese: 'Estou procurando...',
    spanish: 'Estoy buscando...',
    category: 'Directions',
  },
  {
    english: 'Can you show me on the map?',
    italian: 'Puoi mostrarmi sulla mappa?',
    japanese: '地図で教えてもらえますか [chizu de oshiete moraemasu ka]',
    czech: 'Můžete mi to ukázat na mapě?',
    portuguese: 'Você pode me mostrar no mapa?',
    spanish: '¿Puede enseñarme en el mapa?',
    category: 'Directions',
  },
];
