export type VocabularyWord = {
  english: string;
  italian: string;
  japanese: string;
  czech: string;
  portuguese: string;
  spanish: string;
  category: string;
};

export const vocabulary: VocabularyWord[] = [
  // Greetings
  {
    english: 'Hello',
    italian: 'Ciao',
    japanese: 'こんにちは [konnichiwa]',
    czech: 'Ahoj',
    portuguese: 'Olá',
    spanish: 'Hola',
    category: 'Greetings',
  },
  {
    english: 'Good morning',
    italian: 'Buongiorno',
    japanese: 'おはよう [ohayou]',
    czech: 'Dobré ráno',
    portuguese: 'Bom dia',
    spanish: 'Buenos días',
    category: 'Greetings',
  },
  {
    english: 'Good evening',
    italian: 'Buonasera',
    japanese: 'こんばんは [konbanwa]',
    czech: 'Dobrý večer',
    portuguese: 'Boa noite',
    spanish: 'Buenas tardes',
    category: 'Greetings',
  },
  {
    english: 'Goodbye',
    italian: 'Arrivederci',
    japanese: 'さようなら [sayounara]',
    czech: 'Sbohem',
    portuguese: 'Tchau',
    spanish: 'Adiós',
    category: 'Greetings',
  },
  {
    english: 'Please',
    italian: 'Per favore',
    japanese: 'お願いします [onegaishimasu]',
    czech: 'Prosím',
    portuguese: 'Por favor',
    spanish: 'Por favor',
    category: 'Greetings',
  },
  {
    english: 'Thank you',
    italian: 'Grazie',
    japanese: 'ありがとう [arigatou]',
    czech: 'Děkuji',
    portuguese: 'Obrigado',
    spanish: 'Gracias',
    category: 'Greetings',
  },
  {
    english: "You're welcome",
    italian: 'Prego',
    japanese: 'どういたしまして [douitashimashite]',
    czech: 'Prosím',
    portuguese: 'De nada',
    spanish: 'De nada',
    category: 'Greetings',
  },

  // Numbers
  {
    english: 'One',
    italian: 'Uno',
    japanese: '一 [ichi]',
    czech: 'Jeden',
    portuguese: 'Um',
    spanish: 'Uno',
    category: 'Numbers',
  },
  {
    english: 'Two',
    italian: 'Due',
    japanese: '二 [ni]',
    czech: 'Dva',
    portuguese: 'Dois',
    spanish: 'Dos',
    category: 'Numbers',
  },
  {
    english: 'Three',
    italian: 'Tre',
    japanese: '三 [san]',
    czech: 'Tři',
    portuguese: 'Três',
    spanish: 'Tres',
    category: 'Numbers',
  },
  {
    english: 'Four',
    italian: 'Quattro',
    japanese: '四 [yon/shi]',
    czech: 'Čtyři',
    portuguese: 'Quatro',
    spanish: 'Cuatro',
    category: 'Numbers',
  },
  {
    english: 'Five',
    italian: 'Cinque',
    japanese: '五 [go]',
    czech: 'Pět',
    portuguese: 'Cinco',
    spanish: 'Cinco',
    category: 'Numbers',
  },
  {
    english: 'Six',
    italian: 'Sei',
    japanese: '六 [roku]',
    czech: 'Šest',
    portuguese: 'Seis',
    spanish: 'Seis',
    category: 'Numbers',
  },
  {
    english: 'Seven',
    italian: 'Sette',
    japanese: '七 [nana/shichi]',
    czech: 'Sedm',
    portuguese: 'Sete',
    spanish: 'Siete',
    category: 'Numbers',
  },
  {
    english: 'Eight',
    italian: 'Otto',
    japanese: '八 [hachi]',
    czech: 'Osm',
    portuguese: 'Oito',
    spanish: 'Ocho',
    category: 'Numbers',
  },
  {
    english: 'Nine',
    italian: 'Nove',
    japanese: '九 [kyuu/ku]',
    czech: 'Devět',
    portuguese: 'Nove',
    spanish: 'Nueve',
    category: 'Numbers',
  },
  {
    english: 'Ten',
    italian: 'Dieci',
    japanese: '十 [juu]',
    czech: 'Deset',
    portuguese: 'Dez',
    spanish: 'Diez',
    category: 'Numbers',
  },

  // Food
  {
    english: 'Water',
    italian: 'Acqua',
    japanese: '水 [mizu]',
    czech: 'Voda',
    portuguese: 'Água',
    spanish: 'Agua',
    category: 'Food',
  },
  {
    english: 'Bread',
    italian: 'Pane',
    japanese: 'パン [pan]',
    czech: 'Chléb',
    portuguese: 'Pão',
    spanish: 'Pan',
    category: 'Food',
  },
  {
    english: 'Wine',
    italian: 'Vino',
    japanese: 'ワイン [wain]',
    czech: 'Víno',
    portuguese: 'Vinho',
    spanish: 'Vino',
    category: 'Food',
  },
  {
    english: 'Coffee',
    italian: 'Caffè',
    japanese: 'コーヒー [koohii]',
    czech: 'Káva',
    portuguese: 'Café',
    spanish: 'Café',
    category: 'Food',
  },
  {
    english: 'Pizza',
    italian: 'Pizza',
    japanese: 'ピザ [piza]',
    czech: 'Pizza',
    portuguese: 'Pizza',
    spanish: 'Pizza',
    category: 'Food',
  },
  {
    english: 'Pasta',
    italian: 'Pasta',
    japanese: 'パスタ [pasuta]',
    czech: 'Těstoviny',
    portuguese: 'Massa',
    spanish: 'Pasta',
    category: 'Food',
  },
  {
    english: 'Ice cream',
    italian: 'Gelato',
    japanese: 'アイスクリーム [aisu kuriimu]',
    czech: 'Zmrzlina',
    portuguese: 'Sorvete',
    spanish: 'Helado',
    category: 'Food',
  },
  {
    english: 'Cheese',
    italian: 'Formaggio',
    japanese: 'チーズ [chiizu]',
    czech: 'Sýr',
    portuguese: 'Queijo',
    spanish: 'Queso',
    category: 'Food',
  },
  {
    english: 'Meat',
    italian: 'Carne',
    japanese: '肉 [niku]',
    czech: 'Maso',
    portuguese: 'Carne',
    spanish: 'Carne',
    category: 'Food',
  },
  {
    english: 'Fish',
    italian: 'Pesce',
    japanese: '魚 [sakana]',
    czech: 'Ryba',
    portuguese: 'Peixe',
    spanish: 'Pescado',
    category: 'Food',
  },

  // Common words
  {
    english: 'Yes',
    italian: 'Sì',
    japanese: 'はい [hai]',
    czech: 'Ano',
    portuguese: 'Sim',
    spanish: 'Sí',
    category: 'Common',
  },
  {
    english: 'No',
    italian: 'No',
    japanese: 'いいえ [iie]',
    czech: 'Ne',
    portuguese: 'Não',
    spanish: 'No',
    category: 'Common',
  },
  {
    english: 'House',
    italian: 'Casa',
    japanese: '家 [ie]',
    czech: 'Dům',
    portuguese: 'Casa',
    spanish: 'Casa',
    category: 'Common',
  },
  {
    english: 'Family',
    italian: 'Famiglia',
    japanese: '家族 [kazoku]',
    czech: 'Rodina',
    portuguese: 'Família',
    spanish: 'Familia',
    category: 'Common',
  },
  {
    english: 'Friend',
    italian: 'Amico',
    japanese: '友達 [tomodachi]',
    czech: 'Přítel',
    portuguese: 'Amigo',
    spanish: 'Amigo',
    category: 'Common',
  },
  {
    english: 'Love',
    italian: 'Amore',
    japanese: '愛 [ai]',
    czech: 'Láska',
    portuguese: 'Amor',
    spanish: 'Amor',
    category: 'Common',
  },
  {
    english: 'Beautiful',
    italian: 'Bello',
    japanese: '美しい [utsukushii]',
    czech: 'Krásný',
    portuguese: 'Bonito',
    spanish: 'Hermoso',
    category: 'Common',
  },
  {
    english: 'Good',
    italian: 'Buono',
    japanese: '良い [yoi/ii]',
    czech: 'Dobrý',
    portuguese: 'Bom',
    spanish: 'Bueno',
    category: 'Common',
  },
  {
    english: 'Bad',
    italian: 'Cattivo',
    japanese: '悪い [warui]',
    czech: 'Špatný',
    portuguese: 'Mau',
    spanish: 'Malo',
    category: 'Common',
  },
  {
    english: 'Big',
    italian: 'Grande',
    japanese: '大きい [ookii]',
    czech: 'Velký',
    portuguese: 'Grande',
    spanish: 'Grande',
    category: 'Common',
  },
  {
    english: 'Small',
    italian: 'Piccolo',
    japanese: '小さい [chiisai]',
    czech: 'Malý',
    portuguese: 'Pequeno',
    spanish: 'Pequeño',
    category: 'Common',
  },

  // Days
  {
    english: 'Monday',
    italian: 'Lunedì',
    japanese: '月曜日 [getsuyoubi]',
    czech: 'Pondělí',
    portuguese: 'Segunda-feira',
    spanish: 'Lunes',
    category: 'Days',
  },
  {
    english: 'Tuesday',
    italian: 'Martedì',
    japanese: '火曜日 [kayoubi]',
    czech: 'Úterý',
    portuguese: 'Terça-feira',
    spanish: 'Martes',
    category: 'Days',
  },
  {
    english: 'Wednesday',
    italian: 'Mercoledì',
    japanese: '水曜日 [suiyoubi]',
    czech: 'Středa',
    portuguese: 'Quarta-feira',
    spanish: 'Miércoles',
    category: 'Days',
  },
  {
    english: 'Thursday',
    italian: 'Giovedì',
    japanese: '木曜日 [mokuyoubi]',
    czech: 'Čtvrtek',
    portuguese: 'Quinta-feira',
    spanish: 'Jueves',
    category: 'Days',
  },
  {
    english: 'Friday',
    italian: 'Venerdì',
    japanese: '金曜日 [kinyoubi]',
    czech: 'Pátek',
    portuguese: 'Sexta-feira',
    spanish: 'Viernes',
    category: 'Days',
  },
  {
    english: 'Saturday',
    italian: 'Sabato',
    japanese: '土曜日 [doyoubi]',
    czech: 'Sobota',
    portuguese: 'Sábado',
    spanish: 'Sábado',
    category: 'Days',
  },
  {
    english: 'Sunday',
    italian: 'Domenica',
    japanese: '日曜日 [nichiyoubi]',
    czech: 'Neděle',
    portuguese: 'Domingo',
    spanish: 'Domingo',
    category: 'Days',
  },

  // Basic Verbs
  {
    english: 'To be',
    italian: 'Essere',
    japanese: 'です [desu]',
    czech: 'Být',
    portuguese: 'Ser/Estar',
    spanish: 'Ser/Estar',
    category: 'Verbs',
  },
  {
    english: 'To have',
    italian: 'Avere',
    japanese: '持つ [motsu]',
    czech: 'Mít',
    portuguese: 'Ter',
    spanish: 'Tener',
    category: 'Verbs',
  },
  {
    english: 'To do/make',
    italian: 'Fare',
    japanese: 'する [suru]',
    czech: 'Dělat',
    portuguese: 'Fazer',
    spanish: 'Hacer',
    category: 'Verbs',
  },
  {
    english: 'To go',
    italian: 'Andare',
    japanese: '行く [iku]',
    czech: 'Jít',
    portuguese: 'Ir',
    spanish: 'Ir',
    category: 'Verbs',
  },
  {
    english: 'To come',
    italian: 'Venire',
    japanese: '来る [kuru]',
    czech: 'Přijít',
    portuguese: 'Vir',
    spanish: 'Venir',
    category: 'Verbs',
  },
  {
    english: 'To want',
    italian: 'Volere',
    japanese: '欲しい [hoshii]',
    czech: 'Chtít',
    portuguese: 'Querer',
    spanish: 'Querer',
    category: 'Verbs',
  },
  {
    english: 'To eat',
    italian: 'Mangiare',
    japanese: '食べる [taberu]',
    czech: 'Jíst',
    portuguese: 'Comer',
    spanish: 'Comer',
    category: 'Verbs',
  },
  {
    english: 'To drink',
    italian: 'Bere',
    japanese: '飲む [nomu]',
    czech: 'Pít',
    portuguese: 'Beber',
    spanish: 'Beber',
    category: 'Verbs',
  },
  {
    english: 'To see',
    italian: 'Vedere',
    japanese: '見る [miru]',
    czech: 'Vidět',
    portuguese: 'Ver',
    spanish: 'Ver',
    category: 'Verbs',
  },
  {
    english: 'To speak',
    italian: 'Parlare',
    japanese: '話す [hanasu]',
    czech: 'Mluvit',
    portuguese: 'Falar',
    spanish: 'Hablar',
    category: 'Verbs',
  },
  {
    english: 'To understand',
    italian: 'Capire',
    japanese: '分かる [wakaru]',
    czech: 'Rozumět',
    portuguese: 'Entender',
    spanish: 'Entender',
    category: 'Verbs',
  },
  {
    english: 'To know',
    italian: 'Sapere',
    japanese: '知る [shiru]',
    czech: 'Vědět',
    portuguese: 'Saber',
    spanish: 'Saber',
    category: 'Verbs',
  },
  {
    english: 'To think',
    italian: 'Pensare',
    japanese: '思う [omou]',
    czech: 'Myslet',
    portuguese: 'Pensar',
    spanish: 'Pensar',
    category: 'Verbs',
  },
  {
    english: 'To work',
    italian: 'Lavorare',
    japanese: '働く [hataraku]',
    czech: 'Pracovat',
    portuguese: 'Trabalhar',
    spanish: 'Trabajar',
    category: 'Verbs',
  },
  {
    english: 'To sleep',
    italian: 'Dormire',
    japanese: '寝る [neru]',
    czech: 'Spát',
    portuguese: 'Dormir',
    spanish: 'Dormir',
    category: 'Verbs',
  },
  {
    english: 'To live',
    italian: 'Vivere',
    japanese: '住む [sumu]',
    czech: 'Žít',
    portuguese: 'Viver',
    spanish: 'Vivir',
    category: 'Verbs',
  },
  {
    english: 'To buy',
    italian: 'Comprare',
    japanese: '買う [kau]',
    czech: 'Kupovat',
    portuguese: 'Comprar',
    spanish: 'Comprar',
    category: 'Verbs',
  },
  {
    english: 'To sell',
    italian: 'Vendere',
    japanese: '売る [uru]',
    czech: 'Prodávat',
    portuguese: 'Vender',
    spanish: 'Vender',
    category: 'Verbs',
  },
  {
    english: 'To read',
    italian: 'Leggere',
    japanese: '読む [yomu]',
    czech: 'Číst',
    portuguese: 'Ler',
    spanish: 'Leer',
    category: 'Verbs',
  },
  {
    english: 'To write',
    italian: 'Scrivere',
    japanese: '書く [kaku]',
    czech: 'Psát',
    portuguese: 'Escrever',
    spanish: 'Escribir',
    category: 'Verbs',
  },

  // Question Words
  {
    english: 'What',
    italian: 'Cosa/Che',
    japanese: '何 [nani]',
    czech: 'Co',
    portuguese: 'O quê',
    spanish: 'Qué',
    category: 'Questions',
  },
  {
    english: 'Where',
    italian: 'Dove',
    japanese: 'どこ [doko]',
    czech: 'Kde',
    portuguese: 'Onde',
    spanish: 'Dónde',
    category: 'Questions',
  },
  {
    english: 'When',
    italian: 'Quando',
    japanese: 'いつ [itsu]',
    czech: 'Kdy',
    portuguese: 'Quando',
    spanish: 'Cuándo',
    category: 'Questions',
  },
  {
    english: 'Who',
    italian: 'Chi',
    japanese: '誰 [dare]',
    czech: 'Kdo',
    portuguese: 'Quem',
    spanish: 'Quién',
    category: 'Questions',
  },
  {
    english: 'Why',
    italian: 'Perché',
    japanese: 'なぜ [naze]',
    czech: 'Proč',
    portuguese: 'Por quê',
    spanish: 'Por qué',
    category: 'Questions',
  },
  {
    english: 'How',
    italian: 'Come',
    japanese: 'どう [dou]',
    czech: 'Jak',
    portuguese: 'Como',
    spanish: 'Cómo',
    category: 'Questions',
  },
  {
    english: 'How much',
    italian: 'Quanto',
    japanese: 'いくら [ikura]',
    czech: 'Kolik',
    portuguese: 'Quanto',
    spanish: 'Cuánto',
    category: 'Questions',
  },
  {
    english: 'Which',
    italian: 'Quale',
    japanese: 'どれ [dore]',
    czech: 'Který',
    portuguese: 'Qual',
    spanish: 'Cuál',
    category: 'Questions',
  },
  {
    english: 'How many',
    italian: 'Quanti',
    japanese: 'いくつ [ikutsu]',
    czech: 'Kolik',
    portuguese: 'Quantos',
    spanish: 'Cuántos',
    category: 'Questions',
  },

  // Time Expressions
  {
    english: 'Today',
    italian: 'Oggi',
    japanese: '今日 [kyou]',
    czech: 'Dnes',
    portuguese: 'Hoje',
    spanish: 'Hoy',
    category: 'Time',
  },
  {
    english: 'Tomorrow',
    italian: 'Domani',
    japanese: '明日 [ashita]',
    czech: 'Zítra',
    portuguese: 'Amanhã',
    spanish: 'Mañana',
    category: 'Time',
  },
  {
    english: 'Yesterday',
    italian: 'Ieri',
    japanese: '昨日 [kinou]',
    czech: 'Včera',
    portuguese: 'Ontem',
    spanish: 'Ayer',
    category: 'Time',
  },
  {
    english: 'Now',
    italian: 'Ora/Adesso',
    japanese: '今 [ima]',
    czech: 'Teď',
    portuguese: 'Agora',
    spanish: 'Ahora',
    category: 'Time',
  },
  {
    english: 'Later',
    italian: 'Dopo',
    japanese: '後で [ato de]',
    czech: 'Později',
    portuguese: 'Mais tarde',
    spanish: 'Después',
    category: 'Time',
  },
  {
    english: 'Morning',
    italian: 'Mattina',
    japanese: '朝 [asa]',
    czech: 'Ráno',
    portuguese: 'Manhã',
    spanish: 'Mañana',
    category: 'Time',
  },
  {
    english: 'Afternoon',
    italian: 'Pomeriggio',
    japanese: '午後 [gogo]',
    czech: 'Odpoledne',
    portuguese: 'Tarde',
    spanish: 'Tarde',
    category: 'Time',
  },
  {
    english: 'Evening',
    italian: 'Sera',
    japanese: '夕方 [yuugata]',
    czech: 'večer',
    portuguese: 'Noite',
    spanish: 'Noche',
    category: 'Time',
  },
  {
    english: 'Night',
    italian: 'Notte',
    japanese: '夜 [yoru]',
    czech: 'Noc',
    portuguese: 'Noite',
    spanish: 'Noche',
    category: 'Time',
  },
  {
    english: 'Week',
    italian: 'Settimana',
    japanese: '週 [shuu]',
    czech: 'Týden',
    portuguese: 'Semana',
    spanish: 'Semana',
    category: 'Time',
  },
  {
    english: 'Month',
    italian: 'Mese',
    japanese: '月 [tsuki/getsu]',
    czech: 'Měsíc',
    portuguese: 'Mês',
    spanish: 'Mes',
    category: 'Time',
  },
  {
    english: 'Year',
    italian: 'Anno',
    japanese: '年 [nen]',
    czech: 'Rok',
    portuguese: 'Ano',
    spanish: 'Año',
    category: 'Time',
  },
  {
    english: 'Always',
    italian: 'Sempre',
    japanese: 'いつも [itsumo]',
    czech: 'Vždycky',
    portuguese: 'Sempre',
    spanish: 'Siempre',
    category: 'Time',
  },
  {
    english: 'Never',
    italian: 'Mai',
    japanese: '決して [kesshite]',
    czech: 'Nikdy',
    portuguese: 'Nunca',
    spanish: 'Nunca',
    category: 'Time',
  },
  {
    english: 'Sometimes',
    italian: 'A volte',
    japanese: '時々 [tokidoki]',
    czech: 'Někdy',
    portuguese: 'Às vezes',
    spanish: 'A veces',
    category: 'Time',
  },

  // Family
  {
    english: 'Mother',
    italian: 'Madre',
    japanese: '母 [haha]',
    czech: 'Matka',
    portuguese: 'Mãe',
    spanish: 'Madre',
    category: 'Family',
  },
  {
    english: 'Father',
    italian: 'Padre',
    japanese: '父 [chichi]',
    czech: 'Otec',
    portuguese: 'Pai',
    spanish: 'Padre',
    category: 'Family',
  },
  {
    english: 'Parents',
    italian: 'Genitori',
    japanese: '両親 [ryoushin]',
    czech: 'Rodiče',
    portuguese: 'Pais',
    spanish: 'Padres',
    category: 'Family',
  },
  {
    english: 'Son',
    italian: 'Figlio',
    japanese: '息子 [musuko]',
    czech: 'Syn',
    portuguese: 'Filho',
    spanish: 'Hijo',
    category: 'Family',
  },
  {
    english: 'Daughter',
    italian: 'Figlia',
    japanese: '娘 [musume]',
    czech: 'Dcera',
    portuguese: 'Filha',
    spanish: 'Hija',
    category: 'Family',
  },
  {
    english: 'Brother',
    italian: 'Fratello',
    japanese: '兄弟 [kyoudai]',
    czech: 'Bratr',
    portuguese: 'Irmão',
    spanish: 'Hermano',
    category: 'Family',
  },
  {
    english: 'Sister',
    italian: 'Sorella',
    japanese: '姉妹 [shimai]',
    czech: 'Sestra',
    portuguese: 'Irmã',
    spanish: 'Hermana',
    category: 'Family',
  },
  {
    english: 'Grandfather',
    italian: 'Nonno',
    japanese: '祖父 [sofu]',
    czech: 'Dědeček',
    portuguese: 'Avô',
    spanish: 'Abuelo',
    category: 'Family',
  },
  {
    english: 'Grandmother',
    italian: 'Nonna',
    japanese: '祖母 [sobo]',
    czech: 'Babička',
    portuguese: 'Avó',
    spanish: 'Abuela',
    category: 'Family',
  },
  {
    english: 'Husband',
    italian: 'Marito',
    japanese: '夫 [otto]',
    czech: 'Manžel',
    portuguese: 'Marido',
    spanish: 'Esposo',
    category: 'Family',
  },
  {
    english: 'Wife',
    italian: 'Moglie',
    japanese: '妻 [tsuma]',
    czech: 'Manželka',
    portuguese: 'Esposa',
    spanish: 'Esposa',
    category: 'Family',
  },
  {
    english: 'Child',
    italian: 'Bambino',
    japanese: '子供 [kodomo]',
    czech: 'Dítě',
    portuguese: 'Criança',
    spanish: 'Niño',
    category: 'Family',
  },
  {
    english: 'Baby',
    italian: 'Bebè',
    japanese: '赤ちゃん [akachan]',
    czech: 'Mimino',
    portuguese: 'Bebê',
    spanish: 'Bebé',
    category: 'Family',
  },

  // Colors
  {
    english: 'Red',
    italian: 'Rosso',
    japanese: '赤 [aka]',
    czech: 'Červená',
    portuguese: 'Vermelho',
    spanish: 'Rojo',
    category: 'Colors',
  },
  {
    english: 'Blue',
    italian: 'Blu',
    japanese: '青 [ao]',
    czech: 'Modrá',
    portuguese: 'Azul',
    spanish: 'Azul',
    category: 'Colors',
  },
  {
    english: 'Green',
    italian: 'Verde',
    japanese: '緑 [midori]',
    czech: 'Zelená',
    portuguese: 'Verde',
    spanish: 'Verde',
    category: 'Colors',
  },
  {
    english: 'Yellow',
    italian: 'Giallo',
    japanese: '黄色 [kiiro]',
    czech: 'Žlutá',
    portuguese: 'Amarelo',
    spanish: 'Amarillo',
    category: 'Colors',
  },
  {
    english: 'Black',
    italian: 'Nero',
    japanese: '黒 [kuro]',
    czech: 'Černá',
    portuguese: 'Preto',
    spanish: 'Negro',
    category: 'Colors',
  },
  {
    english: 'White',
    italian: 'Bianco',
    japanese: '白 [shiro]',
    czech: 'Bílá',
    portuguese: 'Branco',
    spanish: 'Blanco',
    category: 'Colors',
  },
  {
    english: 'Orange',
    italian: 'Arancione',
    japanese: 'オレンジ [orenji]',
    czech: 'Oranžová',
    portuguese: 'Laranja',
    spanish: 'Naranja',
    category: 'Colors',
  },
  {
    english: 'Purple',
    italian: 'Viola',
    japanese: '紫 [murasaki]',
    czech: 'Fialová',
    portuguese: 'Roxo',
    spanish: 'Morado',
    category: 'Colors',
  },
  {
    english: 'Pink',
    italian: 'Rosa',
    japanese: 'ピンク [pinku]',
    czech: 'Růžová',
    portuguese: 'Rosa',
    spanish: 'Rosa',
    category: 'Colors',
  },
  {
    english: 'Brown',
    italian: 'Marrone',
    japanese: '茶色 [chairo]',
    czech: 'Hnědá',
    portuguese: 'Marrom',
    spanish: 'Marrón',
    category: 'Colors',
  },
  {
    english: 'Gray',
    italian: 'Grigio',
    japanese: '灰色 [haiiro]',
    czech: 'Šedá',
    portuguese: 'Cinza',
    spanish: 'Gris',
    category: 'Colors',
  },

  // Grammar Words - Pronouns
  {
    english: 'I',
    italian: 'Io',
    japanese: '私 [watashi]',
    czech: 'Já',
    portuguese: 'Eu',
    spanish: 'Yo',
    category: 'Grammar',
  },
  {
    english: 'You',
    italian: 'Tu',
    japanese: 'あなた [anata]',
    czech: 'Ty',
    portuguese: 'Você',
    spanish: 'Tú',
    category: 'Grammar',
  },
  {
    english: 'He',
    italian: 'Lui',
    japanese: '彼 [kare]',
    czech: 'On',
    portuguese: 'Ele',
    spanish: 'Él',
    category: 'Grammar',
  },
  {
    english: 'She',
    italian: 'Lei',
    japanese: '彼女 [kanojo]',
    czech: 'Ona',
    portuguese: 'Ela',
    spanish: 'Ella',
    category: 'Grammar',
  },
  {
    english: 'We',
    italian: 'Noi',
    japanese: '私たち [watashitachi]',
    czech: 'My',
    portuguese: 'Nós',
    spanish: 'Nosotros',
    category: 'Grammar',
  },
  {
    english: 'They',
    italian: 'Loro',
    japanese: '彼ら [karera]',
    czech: 'Oni',
    portuguese: 'Eles',
    spanish: 'Ellos',
    category: 'Grammar',
  },

  // Grammar Words - Possessives
  {
    english: 'My',
    italian: 'Mio/Mia',
    japanese: '私の [watashi no]',
    czech: 'Můj/Má',
    portuguese: 'Meu/Minha',
    spanish: 'Mi',
    category: 'Grammar',
  },
  {
    english: 'Your',
    italian: 'Tuo/Tua',
    japanese: 'あなたの [anata no]',
    czech: 'Tvůj/Tvá',
    portuguese: 'Seu/Sua',
    spanish: 'Tu',
    category: 'Grammar',
  },
  {
    english: 'His',
    italian: 'Suo',
    japanese: '彼の [kare no]',
    czech: 'Jeho',
    portuguese: 'Dele',
    spanish: 'Su',
    category: 'Grammar',
  },
  {
    english: 'Her',
    italian: 'Suo/Sua',
    japanese: '彼女の [kanojo no]',
    czech: 'Její',
    portuguese: 'Dela',
    spanish: 'Su',
    category: 'Grammar',
  },
  {
    english: 'Our',
    italian: 'Nostro/Nostra',
    japanese: '私たちの [watashitachi no]',
    czech: 'Náš',
    portuguese: 'Nosso/Nossa',
    spanish: 'Nuestro',
    category: 'Grammar',
  },
  {
    english: 'Their',
    italian: 'Loro',
    japanese: '彼らの [karera no]',
    czech: 'Jejich',
    portuguese: 'Deles/Delas',
    spanish: 'Su',
    category: 'Grammar',
  },

  // Grammar Words - Articles & Prepositions
  {
    english: 'The',
    italian: 'Il/La/Lo/Gli/Le',
    japanese: 'その [sono]',
    czech: 'Ten/Ta/To',
    portuguese: 'O/A/Os/As',
    spanish: 'El/La/Los/Las',
    category: 'Grammar',
  },
  {
    english: 'A/An',
    italian: 'Un/Una',
    japanese: '一つの [hitotsu no]',
    czech: 'Jeden/Jedna',
    portuguese: 'Um/Uma',
    spanish: 'Un/Una',
    category: 'Grammar',
  },
  {
    english: 'In',
    italian: 'In',
    japanese: '中に [naka ni]',
    czech: 'V/Ve',
    portuguese: 'Em',
    spanish: 'En',
    category: 'Grammar',
  },
  {
    english: 'At',
    italian: 'A/Da',
    japanese: 'で [de]',
    czech: 'Na',
    portuguese: 'Em',
    spanish: 'En',
    category: 'Grammar',
  },
  {
    english: 'On',
    italian: 'Su',
    japanese: '上に [ue ni]',
    czech: 'Na',
    portuguese: 'Em/Sobre',
    spanish: 'En/Sobre',
    category: 'Grammar',
  },
  {
    english: 'To',
    italian: 'A',
    japanese: 'に [ni]',
    czech: 'Do/K',
    portuguese: 'Para',
    spanish: 'A/Para',
    category: 'Grammar',
  },
  {
    english: 'From',
    italian: 'Da',
    japanese: 'から [kara]',
    czech: 'Od/Z',
    portuguese: 'De',
    spanish: 'De/Desde',
    category: 'Grammar',
  },
  {
    english: 'With',
    italian: 'Con',
    japanese: 'と [to]',
    czech: 'S/Se',
    portuguese: 'Com',
    spanish: 'Con',
    category: 'Grammar',
  },
  {
    english: 'For',
    italian: 'Per',
    japanese: 'ために [tame ni]',
    czech: 'Pro',
    portuguese: 'Para',
    spanish: 'Para/Por',
    category: 'Grammar',
  },
  {
    english: 'Of',
    italian: 'Di',
    japanese: 'の [no]',
    czech: 'Z/Ze',
    portuguese: 'De',
    spanish: 'De',
    category: 'Grammar',
  },

  // Grammar Words - Conjunctions & Common Words
  {
    english: 'And',
    italian: 'E',
    japanese: 'と [to]',
    czech: 'A',
    portuguese: 'E',
    spanish: 'Y',
    category: 'Grammar',
  },
  {
    english: 'But',
    italian: 'Ma',
    japanese: 'でも [demo]',
    czech: 'Ale',
    portuguese: 'Mas',
    spanish: 'Pero',
    category: 'Grammar',
  },
  {
    english: 'Or',
    italian: 'O',
    japanese: 'または [mata wa]',
    czech: 'Nebo',
    portuguese: 'Ou',
    spanish: 'O',
    category: 'Grammar',
  },
  {
    english: 'Can',
    italian: 'Posso/Può',
    japanese: 'できる [dekiru]',
    czech: 'Můžu',
    portuguese: 'Posso',
    spanish: 'Puedo',
    category: 'Grammar',
  },
  {
    english: 'Must/Have to',
    italian: 'Devo/Deve',
    japanese: 'しなければならない [shinakereba naranai]',
    czech: 'Musím',
    portuguese: 'Devo',
    spanish: 'Debo/Tengo que',
    category: 'Grammar',
  },
  {
    english: 'Like',
    italian: 'Piace',
    japanese: '好き [suki]',
    czech: 'Líbí se',
    portuguese: 'Gostar',
    spanish: 'Gustar',
    category: 'Grammar',
  },
  {
    english: 'Very',
    italian: 'Molto',
    japanese: 'とても [totemo]',
    czech: 'Velmi',
    portuguese: 'Muito',
    spanish: 'Muy',
    category: 'Grammar',
  },
  {
    english: 'Not',
    italian: 'Non',
    japanese: 'ない [nai]',
    czech: 'Ne',
    portuguese: 'Não',
    spanish: 'No',
    category: 'Grammar',
  },
  {
    english: 'Here',
    italian: 'Qui',
    japanese: 'ここ [koko]',
    czech: 'Zde/Tady',
    portuguese: 'Aqui',
    spanish: 'Aquí',
    category: 'Grammar',
  },
  {
    english: 'There',
    italian: 'Là',
    japanese: 'そこ [soko]',
    czech: 'Tam',
    portuguese: 'Lá',
    spanish: 'Allí',
    category: 'Grammar',
  },
  {
    english: 'This',
    italian: 'Questo/Questa',
    japanese: 'これ [kore]',
    czech: 'Toto/Tento',
    portuguese: 'Este/Esta',
    spanish: 'Este/Esta',
    category: 'Grammar',
  },
  {
    english: 'That',
    italian: 'Quello/Quella',
    japanese: 'それ [sore]',
    czech: 'To/Tamto',
    portuguese: 'Esse/Essa',
    spanish: 'Ese/Esa',
    category: 'Grammar',
  },
  {
    english: 'All',
    italian: 'Tutto/Tutti',
    japanese: '全て [subete]',
    czech: 'Všechno',
    portuguese: 'Tudo',
    spanish: 'Todo',
    category: 'Grammar',
  },
  {
    english: 'Some',
    italian: 'Alcuni',
    japanese: 'いくつか [ikutsuka]',
    czech: 'Některé',
    portuguese: 'Alguns',
    spanish: 'Algunos',
    category: 'Grammar',
  },
  {
    english: 'Many',
    italian: 'Molti',
    japanese: 'たくさん [takusan]',
    czech: 'Mnoho',
    portuguese: 'Muitos',
    spanish: 'Muchos',
    category: 'Grammar',
  },

  // Body Parts
  {
    english: 'Head',
    italian: 'Testa',
    japanese: '頭 [atama]',
    czech: 'Hlava',
    portuguese: 'Cabeça',
    spanish: 'Cabeza',
    category: 'Body',
  },
  {
    english: 'Hair',
    italian: 'Capelli',
    japanese: '髪 [kami]',
    czech: 'Vlasy',
    portuguese: 'Cabelo',
    spanish: 'Cabello',
    category: 'Body',
  },
  {
    english: 'Face',
    italian: 'Viso',
    japanese: '顔 [kao]',
    czech: 'Tvář',
    portuguese: 'Rosto',
    spanish: 'Cara',
    category: 'Body',
  },
  {
    english: 'Eyes',
    italian: 'Occhi',
    japanese: '目 [me]',
    czech: 'Oči',
    portuguese: 'Olhos',
    spanish: 'Ojos',
    category: 'Body',
  },
  {
    english: 'Nose',
    italian: 'Naso',
    japanese: '鼻 [hana]',
    czech: 'Nos',
    portuguese: 'Nariz',
    spanish: 'Nariz',
    category: 'Body',
  },
  {
    english: 'Mouth',
    italian: 'Bocca',
    japanese: '口 [kuchi]',
    czech: 'Ústa',
    portuguese: 'Boca',
    spanish: 'Boca',
    category: 'Body',
  },
  {
    english: 'Teeth',
    italian: 'Denti',
    japanese: '歯 [ha]',
    czech: 'Zuby',
    portuguese: 'Dentes',
    spanish: 'Dientes',
    category: 'Body',
  },
  {
    english: 'Ear',
    italian: 'Orecchio',
    japanese: '耳 [mimi]',
    czech: 'Ucho',
    portuguese: 'Orelha',
    spanish: 'Oreja',
    category: 'Body',
  },
  {
    english: 'Neck',
    italian: 'Collo',
    japanese: '首 [kubi]',
    czech: 'Krk',
    portuguese: 'Pescoço',
    spanish: 'Cuello',
    category: 'Body',
  },
  {
    english: 'Shoulder',
    italian: 'Spalla',
    japanese: '肩 [kata]',
    czech: 'Rameno',
    portuguese: 'Ombro',
    spanish: 'Hombro',
    category: 'Body',
  },
  {
    english: 'Arm',
    italian: 'Braccio',
    japanese: '腕 [ude]',
    czech: 'Paže',
    portuguese: 'Braço',
    spanish: 'Brazo',
    category: 'Body',
  },
  {
    english: 'Hand',
    italian: 'Mano',
    japanese: '手 [te]',
    czech: 'Ruka',
    portuguese: 'Mão',
    spanish: 'Mano',
    category: 'Body',
  },
  {
    english: 'Finger',
    italian: 'Dito',
    japanese: '指 [yubi]',
    czech: 'Prst',
    portuguese: 'Dedo',
    spanish: 'Dedo',
    category: 'Body',
  },
  {
    english: 'Chest',
    italian: 'Petto',
    japanese: '胸 [mune]',
    czech: 'Hrudík',
    portuguese: 'Peito',
    spanish: 'Pecho',
    category: 'Body',
  },
  {
    english: 'Back',
    italian: 'Schiena',
    japanese: '背中 [senaka]',
    czech: 'Záda',
    portuguese: 'Costas',
    spanish: 'Espalda',
    category: 'Body',
  },
  {
    english: 'Stomach',
    italian: 'Pancia',
    japanese: 'お腹 [onaka]',
    czech: 'Břicho',
    portuguese: 'Barriga',
    spanish: 'Estómago',
    category: 'Body',
  },
  {
    english: 'Leg',
    italian: 'Gamba',
    japanese: '足 [ashi]',
    czech: 'Noha',
    portuguese: 'Perna',
    spanish: 'Pierna',
    category: 'Body',
  },
  {
    english: 'Knee',
    italian: 'Ginocchio',
    japanese: '膝 [hiza]',
    czech: 'Koleno',
    portuguese: 'Joelho',
    spanish: 'Rodilla',
    category: 'Body',
  },
  {
    english: 'Foot',
    italian: 'Piede',
    japanese: '足 [ashi]',
    czech: 'Chodidlo',
    portuguese: 'Pé',
    spanish: 'Pie',
    category: 'Body',
  },

  // Weather & Seasons
  {
    english: 'Hot',
    italian: 'Caldo',
    japanese: '暑い [atsui]',
    czech: 'Horký',
    portuguese: 'Quente',
    spanish: 'Caliente',
    category: 'Weather',
  },
  {
    english: 'Cold',
    italian: 'Freddo',
    japanese: '寒い [samui]',
    czech: 'Studený',
    portuguese: 'Frio',
    spanish: 'Frío',
    category: 'Weather',
  },
  {
    english: 'Warm',
    italian: 'Caldo',
    japanese: '暖かい [atatakai]',
    czech: 'Teplý',
    portuguese: 'Morno',
    spanish: 'Tibio',
    category: 'Weather',
  },
  {
    english: 'Cool',
    italian: 'Fresco',
    japanese: '涼しい [suzushii]',
    czech: 'Chladný',
    portuguese: 'Fresco',
    spanish: 'Fresco',
    category: 'Weather',
  },
  {
    english: 'Sunny',
    italian: 'Soleggiato',
    japanese: '晴れ [hare]',
    czech: 'Slunečný',
    portuguese: 'Ensolarado',
    spanish: 'Soleado',
    category: 'Weather',
  },
  {
    english: 'Rainy',
    italian: 'Piovoso',
    japanese: '雨 [ame]',
    czech: 'Deštivý',
    portuguese: 'Chuvoso',
    spanish: 'Lluvioso',
    category: 'Weather',
  },
  {
    english: 'Cloudy',
    italian: 'Nuvoloso',
    japanese: '曇り [kumori]',
    czech: 'Zatažený',
    portuguese: 'Nublado',
    spanish: 'Nublado',
    category: 'Weather',
  },
  {
    english: 'Windy',
    italian: 'Ventoso',
    japanese: '風が強い [kaze ga tsuyoi]',
    czech: 'Větrný',
    portuguese: 'Ventoso',
    spanish: 'Ventoso',
    category: 'Weather',
  },
  {
    english: 'Snowy',
    italian: 'Nevoso',
    japanese: '雪 [yuki]',
    czech: 'Sněžný',
    portuguese: 'Nevado',
    spanish: 'Nevado',
    category: 'Weather',
  },
  {
    english: 'Spring',
    italian: 'Primavera',
    japanese: '春 [haru]',
    czech: 'Jaro',
    portuguese: 'Primavera',
    spanish: 'Primavera',
    category: 'Weather',
  },
  {
    english: 'Summer',
    italian: 'Estate',
    japanese: '夏 [natsu]',
    czech: 'Léto',
    portuguese: 'Verão',
    spanish: 'Verano',
    category: 'Weather',
  },
  {
    english: 'Autumn/Fall',
    italian: 'Autunno',
    japanese: '秋 [aki]',
    czech: 'Podzim',
    portuguese: 'Outono',
    spanish: 'Otoño',
    category: 'Weather',
  },
  {
    english: 'Winter',
    italian: 'Inverno',
    japanese: '冬 [fuyu]',
    czech: 'Zima',
    portuguese: 'Inverno',
    spanish: 'Invierno',
    category: 'Weather',
  },

  // Technology
  {
    english: 'Phone',
    italian: 'Telefono',
    japanese: '電話 [denwa]',
    czech: 'Telefon',
    portuguese: 'Telefone',
    spanish: 'Teléfono',
    category: 'Technology',
  },
  {
    english: 'Computer',
    italian: 'Computer',
    japanese: 'コンピューター [konpyuutaa]',
    czech: 'Počítač',
    portuguese: 'Computador',
    spanish: 'Computadora',
    category: 'Technology',
  },
  {
    english: 'Internet',
    italian: 'Internet',
    japanese: 'インターネット [intaanetto]',
    czech: 'Internet',
    portuguese: 'Internet',
    spanish: 'Internet',
    category: 'Technology',
  },
  {
    english: 'WiFi',
    italian: 'WiFi',
    japanese: 'WiFi [waifai]',
    czech: 'WiFi',
    portuguese: 'WiFi',
    spanish: 'WiFi',
    category: 'Technology',
  },
  {
    english: 'Email',
    italian: 'Email',
    japanese: 'メール [meeru]',
    czech: 'Email',
    portuguese: 'Email',
    spanish: 'Email',
    category: 'Technology',
  },
  {
    english: 'Password',
    italian: 'Password',
    japanese: 'パスワード [pasuwaado]',
    czech: 'Heslo',
    portuguese: 'Senha',
    spanish: 'Contraseña',
    category: 'Technology',
  },
  {
    english: 'Charger',
    italian: 'Caricabatterie',
    japanese: '充電器 [juudenki]',
    czech: 'Nabíjačka',
    portuguese: 'Carregador',
    spanish: 'Cargador',
    category: 'Technology',
  },
  {
    english: 'Battery',
    italian: 'Batteria',
    japanese: 'バッテリー [batterii]',
    czech: 'Baterie',
    portuguese: 'Bateria',
    spanish: 'Batería',
    category: 'Technology',
  },
  {
    english: 'Camera',
    italian: 'Fotocamera',
    japanese: 'カメラ [kamera]',
    czech: 'Fotoaparát',
    portuguese: 'Câmera',
    spanish: 'Cámara',
    category: 'Technology',
  },

  // Transportation
  {
    english: 'Car',
    italian: 'Macchina',
    japanese: '車 [kuruma]',
    czech: 'Auto',
    portuguese: 'Carro',
    spanish: 'Coche',
    category: 'Transportation',
  },
  {
    english: 'Bus',
    italian: 'Autobus',
    japanese: 'バス [basu]',
    czech: 'Autobus',
    portuguese: 'Ônibus',
    spanish: 'Autobús',
    category: 'Transportation',
  },
  {
    english: 'Taxi',
    italian: 'Taxi',
    japanese: 'タクシー [takushii]',
    czech: 'Taxi',
    portuguese: 'Táxi',
    spanish: 'Taxi',
    category: 'Transportation',
  },
  {
    english: 'Train',
    italian: 'Treno',
    japanese: '電車 [densha]',
    czech: 'Vlak',
    portuguese: 'Trem',
    spanish: 'Tren',
    category: 'Transportation',
  },
  {
    english: 'Subway',
    italian: 'Metropolitana',
    japanese: '地下鉄 [chikatetsu]',
    czech: 'Metro',
    portuguese: 'Metrô',
    spanish: 'Metro',
    category: 'Transportation',
  },
  {
    english: 'Airplane',
    italian: 'Aereo',
    japanese: '飛行機 [hikouki]',
    czech: 'Letadlo',
    portuguese: 'Avião',
    spanish: 'Avión',
    category: 'Transportation',
  },
  {
    english: 'Bicycle',
    italian: 'Bicicletta',
    japanese: '自転車 [jitensha]',
    czech: 'Kolo',
    portuguese: 'Bicicleta',
    spanish: 'Bicicleta',
    category: 'Transportation',
  },
  {
    english: 'Motorcycle',
    italian: 'Motocicletta',
    japanese: 'バイク [baiku]',
    czech: 'Motorka',
    portuguese: 'Motocicleta',
    spanish: 'Motocicleta',
    category: 'Transportation',
  },
  {
    english: 'Boat',
    italian: 'Barca',
    japanese: '船 [fune]',
    czech: 'Loď',
    portuguese: 'Barco',
    spanish: 'Barco',
    category: 'Transportation',
  },
  {
    english: 'Bus stop',
    italian: "Fermata dell'autobus",
    japanese: 'バス停 [basu tei]',
    czech: 'Autobusová zastávka',
    portuguese: 'Ponto de ônibus',
    spanish: 'Parada de autobús',
    category: 'Transportation',
  },
  {
    english: 'Train station',
    italian: 'Stazione ferroviaria',
    japanese: '駅 [eki]',
    czech: 'Nádraží',
    portuguese: 'Estação de trem',
    spanish: 'Estación de tren',
    category: 'Transportation',
  },
  {
    english: 'Traffic jam',
    italian: 'Ingorgo',
    japanese: '渋滞 [juutai]',
    czech: 'Dopravní zácpa',
    portuguese: 'Engarrafamento',
    spanish: 'Embotellamiento',
    category: 'Transportation',
  },

  // Money & Banking
  {
    english: 'Money',
    italian: 'Soldi',
    japanese: 'お金 [okane]',
    czech: 'Peníze',
    portuguese: 'Dinheiro',
    spanish: 'Dinero',
    category: 'Money',
  },
  {
    english: 'Cash',
    italian: 'Contanti',
    japanese: '現金 [genkin]',
    czech: 'Hotovost',
    portuguese: 'Dinheiro em espécie',
    spanish: 'Efectivo',
    category: 'Money',
  },
  {
    english: 'Credit card',
    italian: 'Carta di credito',
    japanese: 'クレジットカード [kurejitto kaado]',
    czech: 'Kreditní karta',
    portuguese: 'Cartão de crédito',
    spanish: 'Tarjeta de crédito',
    category: 'Money',
  },
  {
    english: 'Bank',
    italian: 'Banca',
    japanese: '銀行 [ginkou]',
    czech: 'Banka',
    portuguese: 'Banco',
    spanish: 'Banco',
    category: 'Money',
  },
  {
    english: 'ATM',
    italian: 'Bancomat',
    japanese: 'ATM [eietiemu]',
    czech: 'Bankomat',
    portuguese: 'Caixa eletrônico',
    spanish: 'Cajero automático',
    category: 'Money',
  },
  {
    english: 'Exchange',
    italian: 'Cambio',
    japanese: '両替 [ryougae]',
    czech: 'Směna',
    portuguese: 'Câmbio',
    spanish: 'Cambio',
    category: 'Money',
  },
  {
    english: 'Receipt',
    italian: 'Ricevuta',
    japanese: 'レシート [reshiito]',
    czech: 'Účtenka',
    portuguese: 'Recibo',
    spanish: 'Recibo',
    category: 'Money',
  },
  {
    english: 'Tip',
    italian: 'Mancia',
    japanese: 'チップ [chippu]',
    czech: 'Sporopné',
    portuguese: 'Gorjeta',
    spanish: 'Propina',
    category: 'Money',
  },
  {
    english: 'Price',
    italian: 'Prezzo',
    japanese: '値段 [nedan]',
    czech: 'Cena',
    portuguese: 'Preço',
    spanish: 'Precio',
    category: 'Money',
  },

  // Directions
  {
    english: 'Left',
    italian: 'Sinistra',
    japanese: '左 [hidari]',
    czech: 'Vlevo',
    portuguese: 'Esquerda',
    spanish: 'Izquierda',
    category: 'Directions',
  },
  {
    english: 'Right',
    italian: 'Destra',
    japanese: '右 [migi]',
    czech: 'Vpravo',
    portuguese: 'Direita',
    spanish: 'Derecha',
    category: 'Directions',
  },
  {
    english: 'Straight',
    italian: 'Dritto',
    japanese: 'まっすぐ [massugu]',
    czech: 'Rovně',
    portuguese: 'Reto',
    spanish: 'Recto',
    category: 'Directions',
  },
  {
    english: 'North',
    italian: 'Nord',
    japanese: '北 [kita]',
    czech: 'Sever',
    portuguese: 'Norte',
    spanish: 'Norte',
    category: 'Directions',
  },
  {
    english: 'South',
    italian: 'Sud',
    japanese: '南 [minami]',
    czech: 'Jih',
    portuguese: 'Sul',
    spanish: 'Sur',
    category: 'Directions',
  },
  {
    english: 'East',
    italian: 'Est',
    japanese: '東 [higashi]',
    czech: 'Východ',
    portuguese: 'Leste',
    spanish: 'Este',
    category: 'Directions',
  },
  {
    english: 'West',
    italian: 'Ovest',
    japanese: '西 [nishi]',
    czech: 'Západ',
    portuguese: 'Oeste',
    spanish: 'Oeste',
    category: 'Directions',
  },
  {
    english: 'Map',
    italian: 'Mappa',
    japanese: '地図 [chizu]',
    czech: 'Mapa',
    portuguese: 'Mapa',
    spanish: 'Mapa',
    category: 'Directions',
  },
  {
    english: 'GPS',
    italian: 'GPS',
    japanese: 'GPS [jiipiesu]',
    czech: 'GPS',
    portuguese: 'GPS',
    spanish: 'GPS',
    category: 'Directions',
  },

  // Places
  {
    english: 'Home',
    italian: 'Casa',
    japanese: '家 [ie/uchi]',
    czech: 'Domov',
    portuguese: 'Casa',
    spanish: 'Casa',
    category: 'Places',
  },
  {
    english: 'School',
    italian: 'Scuola',
    japanese: '学校 [gakkou]',
    czech: 'Škola',
    portuguese: 'Escola',
    spanish: 'Escuela',
    category: 'Places',
  },
  {
    english: 'Work',
    italian: 'Lavoro',
    japanese: '仕事 [shigoto]',
    czech: 'Práce',
    portuguese: 'Trabalho',
    spanish: 'Trabajo',
    category: 'Places',
  },
  {
    english: 'Store',
    italian: 'Negozio',
    japanese: '店 [mise]',
    czech: 'Obchod',
    portuguese: 'Loja',
    spanish: 'Tienda',
    category: 'Places',
  },
  {
    english: 'Restaurant',
    italian: 'Ristorante',
    japanese: 'レストラン [resutoran]',
    czech: 'Restaurace',
    portuguese: 'Restaurante',
    spanish: 'Restaurante',
    category: 'Places',
  },
  {
    english: 'Hotel',
    italian: 'Hotel/Albergo',
    japanese: 'ホテル [hoteru]',
    czech: 'Hotel',
    portuguese: 'Hotel',
    spanish: 'Hotel',
    category: 'Places',
  },
  {
    english: 'Hospital',
    italian: 'Ospedale',
    japanese: '病院 [byouin]',
    czech: 'Nemocnice',
    portuguese: 'Hospital',
    spanish: 'Hospital',
    category: 'Places',
  },
  {
    english: 'Station',
    italian: 'Stazione',
    japanese: '駅 [eki]',
    czech: 'Stanice',
    portuguese: 'Estação',
    spanish: 'Estación',
    category: 'Places',
  },
  {
    english: 'Airport',
    italian: 'Aeroporto',
    japanese: '空港 [kuukou]',
    czech: 'Letiště',
    portuguese: 'Aeroporto',
    spanish: 'Aeropuerto',
    category: 'Places',
  },
  {
    english: 'Bank',
    italian: 'Banca',
    japanese: '銀行 [ginkou]',
    czech: 'Banka',
    portuguese: 'Banco',
    spanish: 'Banco',
    category: 'Places',
  },
  {
    english: 'Post office',
    italian: 'Ufficio postale',
    japanese: '郵便局 [yuubinkyoku]',
    czech: 'Pošta',
    portuguese: 'Correios',
    spanish: 'Oficina de correos',
    category: 'Places',
  },
  {
    english: 'Bathroom',
    italian: 'Bagno',
    japanese: 'トイレ [toire]',
    czech: 'Koupelna',
    portuguese: 'Banheiro',
    spanish: 'Baño',
    category: 'Places',
  },

  // Emotions
  {
    english: 'Happy',
    italian: 'Felice',
    japanese: '嬉しい [ureshii]',
    czech: 'Šťastný',
    portuguese: 'Feliz',
    spanish: 'Feliz',
    category: 'Emotions',
  },
  {
    english: 'Sad',
    italian: 'Triste',
    japanese: '悲しい [kanashii]',
    czech: 'Smutný',
    portuguese: 'Triste',
    spanish: 'Triste',
    category: 'Emotions',
  },
  {
    english: 'Angry',
    italian: 'Arrabbiato',
    japanese: '怒っている [okotte iru]',
    czech: 'Nasrálý',
    portuguese: 'Bravo',
    spanish: 'Enojado',
    category: 'Emotions',
  },
  {
    english: 'Tired',
    italian: 'Stanco',
    japanese: '疲れた [tsukareta]',
    czech: 'Unavoný',
    portuguese: 'Cansado',
    spanish: 'Cansado',
    category: 'Emotions',
  },
  {
    english: 'Hungry',
    italian: 'Affamato',
    japanese: 'お腹すいた [onaka suita]',
    czech: 'Hladný',
    portuguese: 'Com fome',
    spanish: 'Hambriento',
    category: 'Emotions',
  },
  {
    english: 'Thirsty',
    italian: 'Assetato',
    japanese: '喉が渇いた [nodo ga kawaita]',
    czech: 'Žíznivý',
    portuguese: 'Com sede',
    spanish: 'Sediento',
    category: 'Emotions',
  },
  {
    english: 'Sick',
    italian: 'Malato',
    japanese: '病気 [byouki]',
    czech: 'Nemocný',
    portuguese: 'Doente',
    spanish: 'Enfermo',
    category: 'Emotions',
  },
  {
    english: 'Scared',
    italian: 'Spaventato',
    japanese: '怖い [kowai]',
    czech: 'Vystrashený',
    portuguese: 'Assustado',
    spanish: 'Asustado',
    category: 'Emotions',
  },
  {
    english: 'Excited',
    italian: 'Emozionato',
    japanese: 'ワクワク [wakuwaku]',
    czech: 'Vzrušený',
    portuguese: 'Animado',
    spanish: 'Emocionado',
    category: 'Emotions',
  },
  {
    english: 'Bored',
    italian: 'Annoiato',
    japanese: '退屈 [taikutsu]',
    czech: 'Znudaný',
    portuguese: 'Entediado',
    spanish: 'Aburrido',
    category: 'Emotions',
  },
  {
    english: 'Surprised',
    italian: 'Sorpreso',
    japanese: '驚いた [odoroita]',
    czech: 'Překvapený',
    portuguese: 'Surpreso',
    spanish: 'Sorprendido',
    category: 'Emotions',
  },
];
